.gitignore, Makefile, Tiltfile, config/local-development/tilt/add-vault-environment-variables.yaml, config/local-development/tilt/env-replace-image.yaml, config/local-development/tilt/replace-image.yaml, readme.md
=> Fix tilt build

.github/workflows/pr.yaml, .github/workflows/push.yaml
fixes #44 
Signed-off-by: raffaelespazzoli <raffaele.spazzoli@gmail.com>
=> locks go version to 1.16.

api/v1alpha1/commons.go, controllers/vaultsecret_controller.go
=> fixes to work on kube 1.24

Makefile, api/v1alpha1/kubernetesauthengineconfig_webhook.go, api/v1alpha1/kubernetesauthenginerole_types.go, api/v1alpha1/kubernetessecretengineconfig_webhook.go, api/v1alpha1/ldapauthengineconfig_webhook.go, api/v1alpha1/quaysecretengineconfig_webhook.go
=> Fixes #69 

api/v1alpha1/kubernetesauthengineconfig_types.go, api/v1alpha1/utils/commons.go, config/local-development/vault-sa-secret.yaml, controllers/authenginemount_controller.go, controllers/databasesecretengineconfig_controller.go, controllers/databasesecretenginerole_controller.go, controllers/githubsecretengineconfig_controller.go, controllers/githubsecretenginerole_controller.go, controllers/kubernetesauthengineconfig_controller.go, controllers/kubernetesauthenginerole_controller.go, controllers/kubernetessecretengineconfig_controller.go, controllers/kubernetessecretenginerole_controller.go, controllers/ldapauthengineconfig_controller.go, controllers/ldapauthenginegroup_controller.go, controllers/passwordpolicy_controller.go, controllers/pkisecretengineconfig_controller.go, controllers/pkisecretenginerole_controller.go, controllers/policy_controller.go, controllers/quaysecretengineconfig_controller.go, controllers/quaysecretenginerole_controller.go, controllers/quaysecretenginestaticrole_controller.go, controllers/rabbitmqsecretengineconfig_controller.go, controllers/rabbitmqsecretenginerole_controller.go, controllers/randomsecret_controller.go, controllers/secretenginemount_controller.go, readme.md
fixed context reuse issue
fixed jwt token expiration for auth engine
Signed-off-by: raffaelespazzoli <raffaele.spazzoli@gmail.com>
=> fixes kube auth engine jwt token expiration issue

controllers/vaultsecret_controller.go
Signed-off-by: raffaelespazzoli <raffaele.spazzoli@gmail.com>
=> fixed vault secret controller permissions

readme.md
- Added missing section for JWTOIDCAuthEngineRole in readme.md
=> update(): added missing section for JWTOIDCAuthEngineRole in readme.md

api/v1alpha1/databasesecretengineconfig_types.go, api/v1alpha1/databasesecretenginerole_types.go, config/crd/bases/redhatcop.redhat.io_databasesecretengineconfigs.yaml, config/samples/redhatcop_v1alpha1_databasesecretenginestaticrole.yaml, controllers/controllertestutils/decoder.go, controllers/databasesecretenginestaticrole_controller_test.go, controllers/suite_integration_test.go, main.go, test/databasesecretengine/database-engine-admin-policy.yaml, test/databasesecretengine/database-engine-config.yaml, test/databasesecretengine/database-kv-engine-mount.yaml, test/databasesecretengine/database-random-secret.yaml, test/databasesecretengine/database-secret-engine-auth-role.yaml, test/databasesecretengine/database-secret-engine-static-role.yaml, test/databasesecretengine/password-policy.yaml
Also add some tests for DatabaseSecretEngine and DatabaseSecretEngineConfig.
=> Fix DatabaseSecretEngineConfig so that it works with v2 RandomSecret.

config/helmchart/templates/manager.yaml, config/helmchart/values.yaml.tpl
=> Add the ability to specify custom args for the manager container.

api/v1alpha1/randomsecret_types.go
=> fixes #102

api/v1alpha1/kubernetesauthenginerole_types.go, api/v1alpha1/zz_generated.deepcopy.go, config/crd/bases/redhatcop.redhat.io_kubernetesauthengineroles.yaml
=> fixes #112

api/v1alpha1/databasesecretengineconfig_types.go, api/v1alpha1/databasesecretengineconfig_webhook.go, config/crd/bases/redhatcop.redhat.io_databasesecretengineconfigs.yaml
=> fixes #106

readme.md
=> Add documentation for using custom certs with a helm installation.

api/v1alpha1/utils/commons.go
=> fixes #121

readme.md
Updated the parameters used to install database using bitnami/postgresql helm chart to fix issues with securityContext. 
Client Version: 4.11.27
Kustomize Version: v4.5.4
Server Version: 4.11.8
Kubernetes Version: v1.24.0+dc5a2fd
=> Update parameters for Helm install pgsql database

controllers/databasesecretenginestaticrole_controller.go
=> fixed #127

api/v1alpha1/databasesecretengineconfig_types.go
Once the root credentials of a database secret engine has been rotated, the credentials from Kubernetes CR object are not relevant any more, as only Vault knows them: the source of truth for these credentials is now Vault itself.
The vault-config-operator tracks that it performed the root credentials rotation in the `Status` sub-structure of the CR object).
When root credentials rotation is detected, overwriting the Vault-managed credentials with the vault-config-operator ones is prevented: this is achieved by not retrieving these credentials when root rotation already occurred, and not sending these credentials information to vault during the update.
If Vault becomes out-of-sync with the underlying database for some reason and cannot connect any more (example: database is restored from …
=> Fixes #131

config/local-development/vault-values.yaml, controllers/vaultresourcecontroller/vaultengineresourcereconciler.go, controllers/vaultresourcecontroller/vaultpkiengineresourcereconciler.go, controllers/vaultresourcecontroller/vaultresourcereconciler.go
fixes #137 
thanks @davoustp for identifying the issue.
=> fixes #137

api/v1alpha1/utils/commons.go
Fixes https://github.com/redhat-cop/vault-config-operator/issues/139
=> Cache vault clients.

api/v1alpha1/authenginemount_types.go, config/crd/bases/redhatcop.redhat.io_authenginemounts.yaml
=> fixes #152

docs/auth-engines.md
- Optimize documentation for AzureAuthEngineConfig and AzureAuthEngineRole
- Fix typo on documentation
=> fix(): optimize documentation for AzureAuthEngineConfig

api/v1alpha1/randomsecret_types.go, api/v1alpha1/utils/vaultobject.go, config/crd/bases/redhatcop.redhat.io_randomsecrets.yaml, controllers/randomsecret_controller.go, docs/secret-management.md
See https://github.com/redhat-cop/vault-config-operator/issues/196#issuecomment-2419686705 for details
=> #196 RandomSecret retention policy attribute and logic Including one-off existing Vault secret overwrite protection
